title: "KS Boil Water Curriculum"
author: "KS Boil Water Team"
repository:
  url: https://github.com/jbodenheimer/KS_BoilWater_Curriculum
  path_to_book: book
  branch: main
launch_buttons:
  colab_url: "https://colab.research.google.com"
